### ISSUE TITLE
How does getFontBlob() handle composite file formats?

### ISSUE THREAD

**Issue by evanw** [DHNishi/LocalFontAccess#2]
TrueType collection files (_.ttc) and Datafork TrueType files (_.dfont) are composite formats containing multiple fonts. Does getFontBlob() return the raw file verbatim and require the developer to decide which font to use inside that file, or is the user agent responsible for parsing the file and generating a new file that only contains a single font?

**Comment by slightlyoff** [comment]
How important i it to handle these formats?

**Comment by DHNishi** [comment]
Currently, it is the raw file verbatim and the developer is to decide which fonts to use inside the file.

**Comment by evanw** [comment]
That answer is fine in my opinion. It just wasn't called out in the explanation so I figured I'd bring it up. It's very important to handle those formats (OS X has HelveticaNeue.dfont and HelveticaNeueDeskUI.ttc for example) but that can be left up to a library and not to the user agent.
